backend:
  name: git-gateway
  repo: Vera3108/papeles-continuos-website
  branch: main
display_url: https://papeles-continuos.web.app
logo_url: https://papeles-continuos.netlify.app/images/logo.svg
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'

collections:
  - label: 'Papeles Continuos'
    name: 'papelescontinuos'
    format: json
    files:
      - label: PDF's
        name: 'books'
        file: static/content/books.json
        fields:
          - label: PDF
            name: books
            widget: list
            fields:
              - { name: id, label: Id, required: true, widget: text }
              - { name: author, label: Autor, required: true, widget: text }
              - { name: url, label: Archivo, required: true, widget: file }
              - { name: thumbnail, label: Miniatura, required: true, widget: image }
              - name: date
                label: Fecha
                required: true
                widget: date
                default: ''
                format: 'DD MM YYYY'
              - name: tags
                label: Tags
                required: true
                widget: text
      - label: Tags
        name: tags
        file: static/content/tags.json
        fields:
          - { name: tags, label: tags, required: true, widget: text }
